name: Running a Python Script on GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          API_KEY: ${{ secrets.TEMPAPI }}
        run: python hello.py